theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
title: Thomas Wilshaw Notes
description: Random thoughts and notes that will probably mostly be about colour. All thoughts and opinions are mine and quite possibly wrong
author: Thomas Wilshaw

